"""Sync agent memory to agent-readable files (CLAUDE.md, etc.)."""

from __future__ import annotations

from pathlib import Path

from .core import MemoryEngine
from .recall import build_context_brief


CLAUDE_MD_TEMPLATE = """# CLAUDE.md

> Auto-generated by AgentMemory. Do not edit manually -- run `agentmemory sync` instead.

## Project

{project_context}

## Conventions & Preferences

{preferences}

## Recent Decisions

{decisions}

## Known Issues

{errors}

## Architecture

{facts}

---

*Last updated: {timestamp}*
"""


def generate_claude_md(engine: MemoryEngine, project: str) -> str:
    """Generate a CLAUDE.md file from memory."""
    from datetime import datetime, timezone

    ctx = engine.get_project_context(project)
    project_context = ctx.get("description", f"Project: {project}")
    if ctx.get("cwd"):
        project_context += f"\n\nWorking directory: {ctx['cwd']}"

    preferences = engine.recall(project=project, category="preference", limit=20)
    decisions = engine.recall(project=project, category="decision", limit=20)
    errors = engine.recall(project=project, category="error", limit=10)
    facts = engine.recall(project=project, category="fact", limit=20)

    def _fmt(items: list) -> str:
        if not items:
            return "_None recorded yet._"
        return "\n".join(f"- {m.content}" for m in items)

    return CLAUDE_MD_TEMPLATE.format(
        project_context=project_context,
        preferences=_fmt(preferences),
        decisions=_fmt(decisions),
        errors=_fmt(errors),
        facts=_fmt(facts),
        timestamp=datetime.now(timezone.utc).isoformat(),
    )


def sync_project(project: str | None = None, cwd: Path | None = None) -> Path:
    """Sync memory to CLAUDE.md in the project root."""
    from .cli import _get_project

    project = project or _get_project()
    cwd = cwd or Path.cwd()
    engine = MemoryEngine()

    content = generate_claude_md(engine, project)
    claude_md = cwd / "CLAUDE.md"
    claude_md.write_text(content, encoding="utf-8")
    return claude_md
