"""Git hooks integration for Memagent."""

from __future__ import annotations

import os
import stat
from pathlib import Path

POST_COMMIT_HOOK = """#!/bin/sh
# Auto-generated by Memagent -- syncs CLAUDE.md after each commit
# Uses python module path for cross-platform compatibility
python -m memagent.cli sync || memagent sync || true
"""

PRE_COMMIT_HOOK = """#!/bin/sh
# Auto-generated by Memagent -- syncs CLAUDE.md before each commit
# Uses python module path for cross-platform compatibility
python -m memagent.cli sync || memagent sync || true
git add CLAUDE.md
"""


def install_hooks(cwd: Path | None = None) -> tuple[Path, Path]:
    """Install git hooks in the current repo."""
    cwd = cwd or Path.cwd()
    hooks_dir = cwd / ".git" / "hooks"

    if not hooks_dir.exists():
        raise RuntimeError("No .git/hooks directory found. Run `git init` first.")

    post_commit = hooks_dir / "post-commit"
    pre_commit = hooks_dir / "pre-commit"

    # Write post-commit hook
    post_commit.write_text(POST_COMMIT_HOOK, encoding="utf-8")
    os.chmod(post_commit, os.stat(post_commit).st_mode | stat.S_IEXEC)

    # Write pre-commit hook
    pre_commit.write_text(PRE_COMMIT_HOOK, encoding="utf-8")
    os.chmod(pre_commit, os.stat(pre_commit).st_mode | stat.S_IEXEC)

    return pre_commit, post_commit


def uninstall_hooks(cwd: Path | None = None) -> None:
    """Remove Memagent git hooks."""
    cwd = cwd or Path.cwd()
    hooks_dir = cwd / ".git" / "hooks"

    for name in ("post-commit", "pre-commit"):
        hook = hooks_dir / name
        if hook.exists() and "Memagent" in hook.read_text(encoding="utf-8"):
            hook.unlink()
