"""Context retrieval and briefing generation for agents."""

from __future__ import annotations

from .core import MemoryEngine

BRIEF_TEMPLATE = """# Agent Memory Brief — {project}

> This context was automatically generated by Memagent.
> It contains relevant facts, decisions, and preferences from previous sessions.

## Project Context
{project_context}

## Recent Decisions
{decisions}

## Key Facts
{facts}

## Preferences & Conventions
{preferences}

## Known Issues
{errors}

## Recent Actions
{actions}

---
*Loaded from memagent. Type `memagent capture "..."` to add to this context.*
"""


def build_context_brief(engine: MemoryEngine, project: str) -> str:
    """Build a markdown context brief for an AI agent."""
    # Get project context
    ctx = engine.get_project_context(project)
    project_context = ctx.get("description", f"Project: {project}")
    if ctx.get("cwd"):
        project_context += f"\nWorking directory: {ctx['cwd']}"

    # Fetch different categories
    decisions = engine.recall(project=project, category="decision", limit=10)
    facts = engine.recall(project=project, category="fact", limit=10)
    preferences = engine.recall(project=project, category="preference", limit=10)
    errors = engine.recall(project=project, category="error", limit=5)
    actions = engine.recall(project=project, category="action", limit=10)

    def _format_list(memories: list, empty_msg: str = "None recorded yet.") -> str:
        if not memories:
            return empty_msg
        lines = []
        for m in memories:
            prefix = "-"
            if m.confidence < 0.8:
                prefix = "- (confidence: {:.0%})".format(m.confidence)
            lines.append(f"{prefix} {m.content}")
        return "\n".join(lines)

    return BRIEF_TEMPLATE.format(
        project=project,
        project_context=project_context,
        decisions=_format_list(decisions),
        facts=_format_list(facts),
        preferences=_format_list(preferences),
        errors=_format_list(errors),
        actions=_format_list(actions),
    )
